// src/constants/llm-models.ts

import { ModelAttributes } from "../types/config";

export const LLM_MODELS: Record<string, ModelAttributes> = {
  "gemini-3.1-pro-preview": {
    id: "gemini-3.1-pro-preview",
    displayName: "Gemini 3.1 Pro Preview",
    vendor: "GoogleGemini",
    inputContextWindow: "1M",
    outputContextWindow: "65K",
    supportTextToText: true,
    supportImageToText: true,
    supportTextToSpeech: false,
    inputPricePer1mToken: 2.0,
    outputPricePer1mToken: 12.0,
  },
  "gemini-3-flash-preview": {
    id: "gemini-3-flash-preview",
    displayName: "Gemini 3 Flash",
    vendor: "GoogleGemini",
    inputContextWindow: "1M",
    outputContextWindow: "65K",
    supportTextToText: true,
    supportImageToText: true,
    supportTextToSpeech: false,
    inputPricePer1mToken: 0.5,
    outputPricePer1mToken: 3.0,
  },
  "gemini-2.5-flash-preview-tts": {
    id: "gemini-2.5-flash-preview-tts",
    displayName: "Gemini 2.5 Flash Preview TTS",
    vendor: "GoogleGemini",
    inputContextWindow: "8K",
    outputContextWindow: "16K",
    supportTextToText: false,
    supportImageToText: false,
    supportTextToSpeech: true,
    inputPricePer1mToken: 0.5,
    outputPricePer1mToken: 10.0,
  },
  "gpt-5.1-2025-11-13": {
    id: "gpt-5.1-2025-11-13",
    displayName: "GPT-5.1",
    vendor: "OpenAI",
    inputContextWindow: "400K",
    outputContextWindow: "128k",
    supportTextToText: true,
    supportImageToText: true,
    supportTextToSpeech: false,
    inputPricePer1mToken: 1.25,
    outputPricePer1mToken: 10.0,
  },
  "gpt-5.4-2026-03-05": {
    id: "gpt-5.4-2026-03-05",
    displayName: "GPT-5.4",
    vendor: "OpenAI",
    inputContextWindow: "1M",
    outputContextWindow: "128k",
    supportTextToText: true,
    supportImageToText: true,
    supportTextToSpeech: false,
    inputPricePer1mToken: 2.5,
    outputPricePer1mToken: 15.0,
  },
  "gpt-4o-mini-tts": {
    id: "gpt-4o-mini-tts",
    displayName: "GPT-4o mini TTS",
    vendor: "OpenAI",
    inputContextWindow: "2K",
    outputContextWindow: "-",
    supportTextToText: false,
    supportImageToText: false,
    supportTextToSpeech: true,
    inputPricePer1mToken: 0.6,
    outputPricePer1mToken: 12.0,
  },
  "claude-opus-4-6": {
    id: "claude-opus-4-6",
    displayName: "Claude Opus 4.6",
    vendor: "Anthropic",
    inputContextWindow: "200K",
    outputContextWindow: "128K",
    supportTextToText: true,
    supportImageToText: true,
    supportTextToSpeech: false,
    inputPricePer1mToken: 5.0,
    outputPricePer1mToken: 25.0,
  },
  "claude-sonnet-4-6": {
    id: "claude-sonnet-4-6",
    displayName: "Claude Sonnet 4.6",
    vendor: "Anthropic",
    inputContextWindow: "200K",
    outputContextWindow: "64K",
    supportTextToText: true,
    supportImageToText: true,
    supportTextToSpeech: false,
    inputPricePer1mToken: 3.0,
    outputPricePer1mToken: 15.0,
  },
};
