import { VKGDTDisciplineCode } from "@/types/discipline";
import { TargetLanguageCode } from "./languages";

export const VKGDT_DISCIPLINE_NAME_I18N: Record<
  VKGDTDisciplineCode,
  Record<TargetLanguageCode, string>
> = {
  // HA
  "HA.PHI": {
    "zh-CN": "哲学",
    "en": "Philosophy",
    "jp": "哲学",
    "es": "Filosofía",
    "fr": "Philosophie",
    "de": "Philosophie",
    "it": "Filosofia",
    "ru": "Философия",
    "pt": "Filosofia",
    "ko": "철학",
    "vi": "Triết học",
    "th": "ปรัชญา",
    "el": "Φιλοσοφία"
  },
  "HA.REL": {
    "zh-CN": "神学与宗教学",
    "en": "Theology & Religious Studies",
    "jp": "神学・宗教学",
    "es": "Teología y estudios religiosos",
    "fr": "Théologie et sciences des religions",
    "de": "Theologie und Religionswissenschaft",
    "it": "Teologia e studi religiosi",
    "ru": "Теология и религиоведение",
    "pt": "Teologia e estudos religiosos",
    "ko": "신학 및 종교학",
    "vi": "Thần học và nghiên cứu tôn giáo",
    "th": "เทววิทยาและศาสนศึกษา",
    "el": "Θεολογία και Θρησκευτικές Σπουδές"
  },
  "HA.ETH": {
    "zh-CN": "伦理学",
    "en": "Ethics",
    "jp": "倫理学",
    "es": "Ética",
    "fr": "Éthique",
    "de": "Ethik",
    "it": "Etica",
    "ru": "Этика",
    "pt": "Ética",
    "ko": "윤리학",
    "vi": "Đạo đức học",
    "th": "จริยศาสตร์",
    "el": "Ηθική"
  },
  "HA.LING": {
    "zh-CN": "语言学",
    "en": "Linguistics",
    "jp": "言語学",
    "es": "Lingüística",
    "fr": "Linguistique",
    "de": "Linguistik",
    "it": "Linguistica",
    "ru": "Лингвистика",
    "pt": "Linguística",
    "ko": "언어학",
    "vi": "Ngôn ngữ học",
    "th": "ภาษาศาสตร์",
    "el": "Γλωσσολογία"
  },
  "HA.LIT": {
    "zh-CN": "文学与文学理论",
    "en": "Literature & Literary Theory",
    "jp": "文学・文学理論",
    "es": "Literatura y teoría literaria",
    "fr": "Littérature et théorie littéraire",
    "de": "Literatur und Literaturtheorie",
    "it": "Letteratura e teoria letteraria",
    "ru": "Литература и литературная теория",
    "pt": "Literatura e teoria literária",
    "ko": "문학 및 문학이론",
    "vi": "Văn học và lý thuyết văn học",
    "th": "วรรณคดีและทฤษฎีวรรณคดี",
    "el": "Λογοτεχνία και Λογοτεχνική Θεωρία"
  },
  "HA.HIST": {
    "zh-CN": "历史学",
    "en": "History",
    "jp": "歴史学",
    "es": "Historia",
    "fr": "Histoire",
    "de": "Geschichte",
    "it": "Storia",
    "ru": "История",
    "pt": "História",
    "ko": "역사학",
    "vi": "Lịch sử",
    "th": "ประวัติศาสตร์",
    "el": "Ιστορία"
  },
  "HA.ARCH": {
    "zh-CN": "考古学与遗产保护",
    "en": "Archaeology & Heritage",
    "jp": "考古学・文化遺産",
    "es": "Arqueología y patrimonio",
    "fr": "Archéologie et patrimoine",
    "de": "Archäologie und Kulturerbe",
    "it": "Archeologia e patrimonio",
    "ru": "Археология и наследие",
    "pt": "Arqueologia e patrimônio",
    "ko": "고고학 및 문화유산",
    "vi": "Khảo cổ học và di sản",
    "th": "โบราณคดีและมรดกทางวัฒนธรรม",
    "el": "Αρχαιολογία και Πολιτιστική Κληρονομιά"
  },
  "HA.ART": {
    "zh-CN": "艺术史与艺术理论",
    "en": "Art History & Theory",
    "jp": "美術史・美術理論",
    "es": "Historia del arte y teoría del arte",
    "fr": "Histoire de l'art et théorie de l'art",
    "de": "Kunstgeschichte und Kunsttheorie",
    "it": "Storia dell'arte e teoria dell'arte",
    "ru": "История искусства и теория искусства",
    "pt": "História da arte e teoria da arte",
    "ko": "미술사 및 미술이론",
    "vi": "Lịch sử nghệ thuật và lý thuyết nghệ thuật",
    "th": "ประวัติศาสตร์ศิลป์และทฤษฎีศิลปะ",
    "el": "Ιστορία της Τέχνης και Θεωρία της Τέχνης"
  },
  "HA.MUS": {
    "zh-CN": "音乐与表演研究",
    "en": "Music & Performance Studies",
    "jp": "音楽・パフォーマンス研究",
    "es": "Música y estudios de la interpretación",
    "fr": "Musique et études de la performance",
    "de": "Musik- und Performance Studies",
    "it": "Musica e studi della performance",
    "ru": "Музыка и исследования перформанса",
    "pt": "Música e estudos de performance",
    "ko": "음악 및 공연연구",
    "vi": "Âm nhạc và nghiên cứu trình diễn",
    "th": "ดนตรีและการศึกษาด้านการแสดง",
    "el": "Μουσική και Σπουδές Παράστασης"
  },

  // SS
  "SS.POL": {
    "zh-CN": "政治学",
    "en": "Political Science",
    "jp": "政治学",
    "es": "Ciencia política",
    "fr": "Science politique",
    "de": "Politikwissenschaft",
    "it": "Scienza politica",
    "ru": "Политология",
    "pt": "Ciência política",
    "ko": "정치학",
    "vi": "Khoa học chính trị",
    "th": "รัฐศาสตร์",
    "el": "Πολιτική Επιστήμη"
  },
  "SS.IR": {
    "zh-CN": "国际关系与安全研究",
    "en": "International Relations & Security Studies",
    "jp": "国際関係・安全保障研究",
    "es": "Relaciones internacionales y estudios de seguridad",
    "fr": "Relations internationales et études de sécurité",
    "de": "Internationale Beziehungen und Sicherheitsstudien",
    "it": "Relazioni internazionali e studi sulla sicurezza",
    "ru": "Международные отношения и исследования безопасности",
    "pt": "Relações internacionais e estudos de segurança",
    "ko": "국제관계 및 안보연구",
    "vi": "Quan hệ quốc tế và nghiên cứu an ninh",
    "th": "ความสัมพันธ์ระหว่างประเทศและความมั่นคง",
    "el": "Διεθνείς Σχέσεις και Σπουδές Ασφάλειας"
  },
  "SS.ECON": {
    "zh-CN": "经济学",
    "en": "Economics",
    "jp": "経済学",
    "es": "Economía",
    "fr": "Économie",
    "de": "Ökonomie (Volkswirtschaftslehre)",
    "it": "Economia",
    "ru": "Экономика",
    "pt": "Economia",
    "ko": "경제학",
    "vi": "Kinh tế học",
    "th": "เศรษฐศาสตร์",
    "el": "Οικονομική Επιστήμη"
  },
  "SS.SOC": {
    "zh-CN": "社会学",
    "en": "Sociology",
    "jp": "社会学",
    "es": "Sociología",
    "fr": "Sociologie",
    "de": "Soziologie",
    "it": "Sociologia",
    "ru": "Социология",
    "pt": "Sociologia",
    "ko": "사회학",
    "vi": "Xã hội học",
    "th": "สังคมวิทยา",
    "el": "Κοινωνιολογία"
  },
  "SS.ANTH": {
    "zh-CN": "人类学与民族志",
    "en": "Anthropology & Ethnography",
    "jp": "人類学・民族誌",
    "es": "Antropología y etnografía",
    "fr": "Anthropologie et ethnographie",
    "de": "Anthropologie und Ethnografie",
    "it": "Antropologia ed etnografia",
    "ru": "Антропология и этнография",
    "pt": "Antropologia e etnografia",
    "ko": "인류학 및 민족지",
    "vi": "Nhân học và dân tộc học",
    "th": "มานุษยวิทยาและชาติพันธุ์วรรณนา",
    "el": "Ανθρωπολογία και Εθνογραφία"
  },
  "SS.GEO": {
    "zh-CN": "人文与经济地理",
    "en": "Human & Economic Geography",
    "jp": "人文・経済地理学",
    "es": "Geografía humana y económica",
    "fr": "Géographie humaine et économique",
    "de": "Humangeographie und Wirtschaftsgeographie",
    "it": "Geografia umana ed economica",
    "ru": "Человеческая и экономическая география",
    "pt": "Geografia humana e econômica",
    "ko": "인문 및 경제지리학",
    "vi": "Địa lý nhân văn và kinh tế",
    "th": "ภูมิศาสตร์มนุษย์และเศรษฐกิจ",
    "el": "Ανθρωπογεωγραφία και Οικονομική Γεωγραφία"
  },
  "SS.LAW": {
    "zh-CN": "法学",
    "en": "Law",
    "jp": "法学",
    "es": "Derecho",
    "fr": "Droit",
    "de": "Rechtswissenschaft",
    "it": "Diritto",
    "ru": "Право",
    "pt": "Direito",
    "ko": "법학",
    "vi": "Luật học",
    "th": "นิติศาสตร์",
    "el": "Νομική"
  },
  "SS.PPA": {
    "zh-CN": "公共政策与公共管理",
    "en": "Public Policy & Public Administration",
    "jp": "公共政策・行政学",
    "es": "Políticas públicas y administración pública",
    "fr": "Politiques publiques et administration publique",
    "de": "Öffentliche Politik und öffentliche Verwaltung",
    "it": "Politiche pubbliche e amministrazione pubblica",
    "ru": "Государственная политика и государственное управление",
    "pt": "Políticas públicas e administração pública",
    "ko": "공공정책 및 행정학",
    "vi": "Chính sách công và hành chính công",
    "th": "นโยบายสาธารณะและการบริหารรัฐกิจ",
    "el": "Δημόσια Πολιτική και Δημόσια Διοίκηση"
  },
  "SS.PSY": {
    "zh-CN": "心理学",
    "en": "Psychology",
    "jp": "心理学",
    "es": "Psicología",
    "fr": "Psychologie",
    "de": "Psychologie",
    "it": "Psicologia",
    "ru": "Психология",
    "pt": "Psicologia",
    "ko": "심리학",
    "vi": "Tâm lý học",
    "th": "จิตวิทยา",
    "el": "Ψυχολογία"
  },
  "SS.EDU": {
    "zh-CN": "教育学",
    "en": "Education",
    "jp": "教育学",
    "es": "Educación",
    "fr": "Sciences de l'éducation",
    "de": "Erziehungswissenschaft",
    "it": "Scienze dell'educazione",
    "ru": "Педагогика",
    "pt": "Educação",
    "ko": "교육학",
    "vi": "Giáo dục học",
    "th": "ศึกษาศาสตร์",
    "el": "Επιστήμες της Εκπαίδευσης"
  },
  "SS.MEDIA": {
    "zh-CN": "媒体与传播",
    "en": "Media & Communication",
    "jp": "メディア・コミュニケーション",
    "es": "Medios y comunicación",
    "fr": "Médias et communication",
    "de": "Medien- und Kommunikationswissenschaft",
    "it": "Media e comunicazione",
    "ru": "Медиа и коммуникация",
    "pt": "Mídia e comunicação",
    "ko": "미디어 및 커뮤니케이션",
    "vi": "Truyền thông và truyền thông đại chúng",
    "th": "สื่อและการสื่อสาร",
    "el": "Μέσα Ενημέρωσης και Επικοινωνία"
  },
  "SS.RHET": {
    "zh-CN": "修辞学与论证",
    "en": "Rhetoric & Argumentation",
    "jp": "修辞学・議論学",
    "es": "Retórica y argumentación",
    "fr": "Rhétorique et argumentation",
    "de": "Rhetorik und Argumentation",
    "it": "Retorica e argomentazione",
    "ru": "Риторика и аргументация",
    "pt": "Retórica e argumentação",
    "ko": "수사학 및 논증",
    "vi": "Tu từ học và lập luận",
    "th": "วาทศิลป์และการโต้แย้ง",
    "el": "Ρητορική και Επιχειρηματολογία"
  },

  // NS
  "NS.MATH": {
    "zh-CN": "数学",
    "en": "Mathematics",
    "jp": "数学",
    "es": "Matemáticas",
    "fr": "Mathématiques",
    "de": "Mathematik",
    "it": "Matematica",
    "ru": "Математика",
    "pt": "Matemática",
    "ko": "수학",
    "vi": "Toán học",
    "th": "คณิตศาสตร์",
    "el": "Μαθηματικά"
  },
  "NS.STAT": {
    "zh-CN": "统计学与概率论",
    "en": "Statistics & Probability",
    "jp": "統計学・確率論",
    "es": "Estadística y probabilidad",
    "fr": "Statistiques et probabilités",
    "de": "Statistik und Wahrscheinlichkeit",
    "it": "Statistica e probabilità",
    "ru": "Статистика и теория вероятностей",
    "pt": "Estatística e probabilidade",
    "ko": "통계학 및 확률론",
    "vi": "Thống kê và xác suất",
    "th": "สถิติและความน่าจะเป็น",
    "el": "Στατιστική και Θεωρία Πιθανοτήτων"
  },
  "NS.PHYS": {
    "zh-CN": "物理学",
    "en": "Physics",
    "jp": "物理学",
    "es": "Física",
    "fr": "Physique",
    "de": "Physik",
    "it": "Fisica",
    "ru": "Физика",
    "pt": "Física",
    "ko": "물리학",
    "vi": "Vật lý",
    "th": "ฟิสิกส์",
    "el": "Φυσική"
  },
  "NS.CHEM": {
    "zh-CN": "化学",
    "en": "Chemistry",
    "jp": "化学",
    "es": "Química",
    "fr": "Chimie",
    "de": "Chemie",
    "it": "Chimica",
    "ru": "Химия",
    "pt": "Química",
    "ko": "화학",
    "vi": "Hóa học",
    "th": "เคมี",
    "el": "Χημεία"
  },
  "NS.ASTRO": {
    "zh-CN": "天文学与天体物理",
    "en": "Astronomy & Astrophysics",
    "jp": "天文学・天体物理学",
    "es": "Astronomía y astrofísica",
    "fr": "Astronomie et astrophysique",
    "de": "Astronomie und Astrophysik",
    "it": "Astronomia e astrofisica",
    "ru": "Астрономия и астрофизика",
    "pt": "Astronomia e astrofísica",
    "ko": "천문학 및 천체물리학",
    "vi": "Thiên văn học và vật lý thiên văn",
    "th": "ดาราศาสตร์และฟิสิกส์ดาราศาสตร์",
    "el": "Αστρονομία και Αστροφυσική"
  },
  "NS.EARTH": {
    "zh-CN": "地球科学",
    "en": "Earth Sciences",
    "jp": "地球科学",
    "es": "Ciencias de la Tierra",
    "fr": "Sciences de la Terre",
    "de": "Geowissenschaften",
    "it": "Scienze della Terra",
    "ru": "Науки о Земле",
    "pt": "Ciências da Terra",
    "ko": "지구과학",
    "vi": "Khoa học Trái Đất",
    "th": "วิทยาศาสตร์โลก",
    "el": "Επιστήμες της Γης"
  },
  "NS.ECO": {
    "zh-CN": "生态学",
    "en": "Ecology",
    "jp": "生態学",
    "es": "Ecología",
    "fr": "Écologie",
    "de": "Ökologie",
    "it": "Ecologia",
    "ru": "Экология",
    "pt": "Ecologia",
    "ko": "생태학",
    "vi": "Sinh thái học",
    "th": "นิเวศวิทยา",
    "el": "Οικολογία"
  },
  "NS.ENV": {
    "zh-CN": "环境科学",
    "en": "Environmental Science",
    "jp": "環境科学",
    "es": "Ciencias ambientales",
    "fr": "Sciences de l'environnement",
    "de": "Umweltwissenschaften",
    "it": "Scienze ambientali",
    "ru": "Науки об окружающей среде",
    "pt": "Ciências ambientais",
    "ko": "환경과학",
    "vi": "Khoa học môi trường",
    "th": "วิทยาศาสตร์สิ่งแวดล้อม",
    "el": "Περιβαλλοντικές Επιστήμες"
  },

  // ET
  "ET.SEMI": {
    "zh-CN": "半导体与微电子",
    "en": "Semiconductors & Microelectronics",
    "jp": "半導体・マイクロエレクトロニクス",
    "es": "Semiconductores y microelectrónica",
    "fr": "Semi-conducteurs et microélectronique",
    "de": "Halbleiter und Mikroelektronik",
    "it": "Semiconduttori e microelettronica",
    "ru": "Полупроводники и микроэлектроника",
    "pt": "Semicondutores e microeletrônica",
    "ko": "반도체 및 마이크로전자공학",
    "vi": "Bán dẫn và vi điện tử",
    "th": "สารกึ่งตัวนำและไมโครอิเล็กทรอนิกส์",
    "el": "Ημιαγωγοί και Μικροηλεκτρονική"
  },
  "ET.CS": {
    "zh-CN": "计算机科学",
    "en": "Computer Science",
    "jp": "コンピュータサイエンス",
    "es": "Ciencias de la computación",
    "fr": "Informatique",
    "de": "Informatik",
    "it": "Informatica",
    "ru": "Компьютерные науки",
    "pt": "Ciência da computação",
    "ko": "컴퓨터 과학",
    "vi": "Khoa học máy tính",
    "th": "วิทยาการคอมพิวเตอร์",
    "el": "Επιστήμη Υπολογιστών"
  },
  "ET.AI": {
    "zh-CN": "人工智能与机器学习",
    "en": "Artificial Intelligence & Machine Learning",
    "jp": "人工知能・機械学習",
    "es": "Inteligencia artificial y aprendizaje automático",
    "fr": "Intelligence artificielle et apprentissage automatique",
    "de": "Künstliche Intelligenz und maschinelles Lernen",
    "it": "Intelligenza artificiale e apprendimento automatico",
    "ru": "Искусственный интеллект и машинное обучение",
    "pt": "Inteligência artificial e aprendizado de máquina",
    "ko": "인공지능 및 머신러닝",
    "vi": "Trí tuệ nhân tạo và học máy",
    "th": "ปัญญาประดิษฐ์และการเรียนรู้ของเครื่อง",
    "el": "Τεχνητή Νοημοσύνη και Μηχανική Μάθηση"
  },
  "ET.DATA": {
    "zh-CN": "数据科学与信息工程",
    "en": "Data Science & Information Engineering",
    "jp": "データサイエンス・情報工学",
    "es": "Ciencia de datos e ingeniería de la información",
    "fr": "Science des données et ingénierie de l'information",
    "de": "Data Science und Informationsengineering",
    "it": "Scienza dei dati e ingegneria dell'informazione",
    "ru": "Наука о данных и информационная инженерия",
    "pt": "Ciência de dados e engenharia da informação",
    "ko": "데이터 과학 및 정보공학",
    "vi": "Khoa học dữ liệu và kỹ thuật thông tin",
    "th": "วิทยาการข้อมูลและวิศวกรรมสารสนเทศ",
    "el": "Επιστήμη Δεδομένων και Μηχανική Πληροφορίας"
  },
  "ET.EE": {
    "zh-CN": "电气工程",
    "en": "Electrical Engineering",
    "jp": "電気工学",
    "es": "Ingeniería eléctrica",
    "fr": "Génie électrique",
    "de": "Elektrotechnik",
    "it": "Ingegneria elettrica",
    "ru": "Электротехника",
    "pt": "Engenharia elétrica",
    "ko": "전기공학",
    "vi": "Kỹ thuật điện",
    "th": "วิศวกรรมไฟฟ้า",
    "el": "Ηλεκτρολογική Μηχανική"
  },
  "ET.NET": {
    "zh-CN": "网络与分布式基础设施",
    "en": "Networking & Distributed Infrastructure",
    "jp": "ネットワーク・分散インフラ",
    "es": "Redes e infraestructura distribuida",
    "fr": "Réseaux et infrastructure distribuée",
    "de": "Netzwerke und verteilte Infrastruktur",
    "it": "Reti e infrastruttura distribuita",
    "ru": "Сети и распределённая инфраструктура",
    "pt": "Redes e infraestrutura distribuída",
    "ko": "네트워킹 및 분산 인프라",
    "vi": "Mạng và hạ tầng phân tán",
    "th": "เครือข่ายและโครงสร้างพื้นฐานแบบกระจาย",
    "el": "Δίκτυα και Κατανεμημένη Υποδομή"
  },
  "ET.SEC": {
    "zh-CN": "网络安全",
    "en": "Cybersecurity",
    "jp": "サイバーセキュリティ",
    "es": "Ciberseguridad",
    "fr": "Cybersécurité",
    "de": "Cybersicherheit",
    "it": "Cybersecurity",
    "ru": "Кибербезопасность",
    "pt": "Cibersegurança",
    "ko": "사이버보안",
    "vi": "An ninh mạng",
    "th": "ความมั่นคงปลอดภัยไซเบอร์",
    "el": "Κυβερνοασφάλεια"
  },
  "ET.HCI": {
    "zh-CN": "人机交互与用户体验（HCI/UX）",
    "en": "Human-Computer Interaction & UX",
    "jp": "ヒューマンコンピュータインタラクション（HCI）・UX",
    "es": "Interacción humano-computadora (HCI) y UX",
    "fr": "Interaction homme-machine (IHM) et UX",
    "de": "Mensch-Computer-Interaktion (HCI) und UX",
    "it": "Interazione uomo-macchina (HCI) e UX",
    "ru": "Взаимодействие человек-компьютер (HCI) и UX",
    "pt": "Interação humano-computador (HCI) e UX",
    "ko": "인간-컴퓨터 상호작용(HCI) 및 UX",
    "vi": "Tương tác người–máy (HCI) và UX",
    "th": "ปฏิสัมพันธ์มนุษย์–คอมพิวเตอร์ (HCI) และ UX",
    "el": "Αλληλεπίδραση Ανθρώπου-Υπολογιστή (HCI) και UX"
  },
  "ET.MECH": {
    "zh-CN": "机械工程",
    "en": "Mechanical Engineering",
    "jp": "機械工学",
    "es": "Ingeniería mecánica",
    "fr": "Génie mécanique",
    "de": "Maschinenbau",
    "it": "Ingegneria meccanica",
    "ru": "Машиностроение",
    "pt": "Engenharia mecânica",
    "ko": "기계공학",
    "vi": "Kỹ thuật cơ khí",
    "th": "วิศวกรรมเครื่องกล",
    "el": "Μηχανολογία"
  },
  "ET.CIV": {
    "zh-CN": "土木与建筑工程",
    "en": "Civil & Architectural Engineering",
    "jp": "土木・建築工学",
    "es": "Ingeniería civil y arquitectónica",
    "fr": "Génie civil et architectural",
    "de": "Bau- und Architekturingenieurwesen",
    "it": "Ingegneria civile e architettonica",
    "ru": "Гражданское и архитектурное строительство",
    "pt": "Engenharia civil e arquitetônica",
    "ko": "토목 및 건축공학",
    "vi": "Kỹ thuật xây dựng và kiến trúc",
    "th": "วิศวกรรมโยธาและสถาปัตยกรรม",
    "el": "Πολιτική Μηχανική και Αρχιτεκτονική"
  },
  "ET.AERO": {
    "zh-CN": "航空航天工程",
    "en": "Aerospace Engineering",
    "jp": "航空宇宙工学",
    "es": "Ingeniería aeroespacial",
    "fr": "Génie aérospatial",
    "de": "Luft- und Raumfahrttechnik",
    "it": "Ingegneria aerospaziale",
    "ru": "Аэрокосмическая инженерия",
    "pt": "Engenharia aeroespacial",
    "ko": "항공우주공학",
    "vi": "Kỹ thuật hàng không vũ trụ",
    "th": "วิศวกรรมการบินและอวกาศ",
    "el": "Αεροδιαστημική Μηχανική"
  },
  "ET.MAT": {
    "zh-CN": "材料科学",
    "en": "Materials Science",
    "jp": "材料科学",
    "es": "Ciencia de materiales",
    "fr": "Science des matériaux",
    "de": "Materialwissenschaft",
    "it": "Scienza dei materiali",
    "ru": "Материаловедение",
    "pt": "Ciência dos materiais",
    "ko": "재료과학",
    "vi": "Khoa học vật liệu",
    "th": "วิทยาศาสตร์วัสดุ",
    "el": "Επιστήμη Υλικών"
  },
  "ET.CHE": {
    "zh-CN": "化学工程",
    "en": "Chemical Engineering",
    "jp": "化学工学",
    "es": "Ingeniería química",
    "fr": "Génie chimique",
    "de": "Chemieingenieurwesen",
    "it": "Ingegneria chimica",
    "ru": "Химическая инженерия",
    "pt": "Engenharia química",
    "ko": "화학공학",
    "vi": "Kỹ thuật hóa học",
    "th": "วิศวกรรมเคมี",
    "el": "Χημική Μηχανική"
  },
  "ET.OR": {
    "zh-CN": "工业工程与运筹学",
    "en": "Industrial Engineering & Operations Research",
    "jp": "経営工学・オペレーションズリサーチ",
    "es": "Ingeniería industrial e investigación operativa",
    "fr": "Génie industriel et recherche opérationnelle",
    "de": "Industrieingenieurwesen und Operations Research",
    "it": "Ingegneria industriale e ricerca operativa",
    "ru": "Промышленная инженерия и исследование операций",
    "pt": "Engenharia industrial e pesquisa operacional",
    "ko": "산업공학 및 운영연구",
    "vi": "Kỹ thuật công nghiệp và nghiên cứu tác nghiệp",
    "th": "วิศวกรรมอุตสาหการและวิจัยปฏิบัติการ",
    "el": "Βιομηχανική Μηχανική και Επιχειρησιακή Έρευνα"
  },

  // ML
  "ML.BIO": {
    "zh-CN": "生物学",
    "en": "Biology",
    "jp": "生物学",
    "es": "Biología",
    "fr": "Biologie",
    "de": "Biologie",
    "it": "Biologia",
    "ru": "Биология",
    "pt": "Biologia",
    "ko": "생물학",
    "vi": "Sinh học",
    "th": "ชีววิทยา",
    "el": "Βιολογία"
  },
  "ML.BIOCHEM": {
    "zh-CN": "生物化学与分子生物学",
    "en": "Biochemistry & Molecular Biology",
    "jp": "生化学・分子生物学",
    "es": "Bioquímica y biología molecular",
    "fr": "Biochimie et biologie moléculaire",
    "de": "Biochemie und Molekularbiologie",
    "it": "Biochimica e biologia molecolare",
    "ru": "Биохимия и молекулярная биология",
    "pt": "Bioquímica e biologia molecular",
    "ko": "생화학 및 분자생물학",
    "vi": "Hóa sinh và sinh học phân tử",
    "th": "ชีวเคมีและชีววิทยาระดับโมเลกุล",
    "el": "Βιοχημεία και Μοριακή Βιολογία"
  },
  "ML.GEN": {
    "zh-CN": "遗传学与基因组学",
    "en": "Genetics & Genomics",
    "jp": "遺伝学・ゲノミクス",
    "es": "Genética y genómica",
    "fr": "Génétique et génomique",
    "de": "Genetik und Genomik",
    "it": "Genetica e genomica",
    "ru": "Генетика и геномика",
    "pt": "Genética e genômica",
    "ko": "유전학 및 유전체학",
    "vi": "Di truyền học và hệ gen học",
    "th": "พันธุศาสตร์และจีโนมิกส์",
    "el": "Γενετική και Γονιδιωματική"
  },
  "ML.MICRO": {
    "zh-CN": "微生物学",
    "en": "Microbiology",
    "jp": "微生物学",
    "es": "Microbiología",
    "fr": "Microbiologie",
    "de": "Mikrobiologie",
    "it": "Microbiologia",
    "ru": "Микробиология",
    "pt": "Microbiologia",
    "ko": "미생물학",
    "vi": "Vi sinh học",
    "th": "จุลชีววิทยา",
    "el": "Μικροβιολογία"
  },
  "ML.IMM": {
    "zh-CN": "免疫学",
    "en": "Immunology",
    "jp": "免疫学",
    "es": "Inmunología",
    "fr": "Immunologie",
    "de": "Immunologie",
    "it": "Immunologia",
    "ru": "Иммунология",
    "pt": "Imunologia",
    "ko": "면역학",
    "vi": "Miễn dịch học",
    "th": "ภูมิคุ้มกันวิทยา",
    "el": "Ανοσολογία"
  },
  "ML.NEURO": {
    "zh-CN": "神经科学",
    "en": "Neuroscience",
    "jp": "神経科学",
    "es": "Neurociencia",
    "fr": "Neurosciences",
    "de": "Neurowissenschaften",
    "it": "Neuroscienze",
    "ru": "Нейронаука",
    "pt": "Neurociência",
    "ko": "신경과학",
    "vi": "Khoa học thần kinh",
    "th": "ประสาทวิทยา",
    "el": "Νευροεπιστήμη"
  },
  "ML.ANP": {
    "zh-CN": "解剖学与生理学",
    "en": "Anatomy & Physiology",
    "jp": "解剖学・生理学",
    "es": "Anatomía y fisiología",
    "fr": "Anatomie et physiologie",
    "de": "Anatomie und Physiologie",
    "it": "Anatomia e fisiologia",
    "ru": "Анатомия и физиология",
    "pt": "Anatomia e fisiologia",
    "ko": "해부학 및 생리학",
    "vi": "Giải phẫu học và sinh lý học",
    "th": "กายวิภาคศาสตร์และสรีรวิทยา",
    "el": "Ανατομία και Φυσιολογία"
  },
  "ML.PHAR": {
    "zh-CN": "药理学与毒理学",
    "en": "Pharmacology & Toxicology",
    "jp": "薬理学・毒性学",
    "es": "Farmacología y toxicología",
    "fr": "Pharmacologie et toxicologie",
    "de": "Pharmakologie und Toxikologie",
    "it": "Farmacologia e tossicologia",
    "ru": "Фармакология и токсикология",
    "pt": "Farmacologia e toxicologia",
    "ko": "약리학 및 독성학",
    "vi": "Dược lý học và độc chất học",
    "th": "เภสัชวิทยาและพิษวิทยา",
    "el": "Φαρμακολογία και Τοξικολογία"
  },
  "ML.CLIN": {
    "zh-CN": "临床医学",
    "en": "Clinical Medicine",
    "jp": "臨床医学",
    "es": "Medicina clínica",
    "fr": "Médecine clinique",
    "de": "Klinische Medizin",
    "it": "Medicina clinica",
    "ru": "Клиническая медицина",
    "pt": "Medicina clínica",
    "ko": "임상의학",
    "vi": "Y học lâm sàng",
    "th": "เวชศาสตร์คลินิก",
    "el": "Κλινική Ιατρική"
  },
  "ML.PH": {
    "zh-CN": "公共卫生与流行病学",
    "en": "Public Health & Epidemiology",
    "jp": "公衆衛生・疫学",
    "es": "Salud pública y epidemiología",
    "fr": "Santé publique et épidémiologie",
    "de": "Öffentliche Gesundheit und Epidemiologie",
    "it": "Sanità pubblica ed epidemiologia",
    "ru": "Общественное здравоохранение и эпидемиология",
    "pt": "Saúde pública e epidemiologia",
    "ko": "공중보건 및 역학",
    "vi": "Y tế công cộng và dịch tễ học",
    "th": "สาธารณสุขและระบาดวิทยา",
    "el": "Δημόσια Υγεία και Επιδημιολογία"
  },
  "ML.BIOINF": {
    "zh-CN": "生物信息学",
    "en": "Bioinformatics",
    "jp": "バイオインフォマティクス",
    "es": "Bioinformática",
    "fr": "Bioinformatique",
    "de": "Bioinformatik",
    "it": "Bioinformatica",
    "ru": "Биоинформатика",
    "pt": "Bioinformática",
    "ko": "생물정보학",
    "vi": "Tin sinh học",
    "th": "ชีวสารสนเทศ",
    "el": "Βιοπληροφορική"
  },

  // BM
  "BM.FIN": {
    "zh-CN": "金融与银行学",
    "en": "Finance & Banking",
    "jp": "金融・銀行学",
    "es": "Finanzas y banca",
    "fr": "Finance et banque",
    "de": "Finanzen und Bankwesen",
    "it": "Finanza e banca",
    "ru": "Финансы и банковское дело",
    "pt": "Finanças e bancos",
    "ko": "금융 및 은행학",
    "vi": "Tài chính và ngân hàng",
    "th": "การเงินและการธนาคาร",
    "el": "Χρηματοοικονομικά και Τραπεζική"
  },
  "BM.MGMT": {
    "zh-CN": "管理与组织",
    "en": "Management & Organization",
    "jp": "経営・組織",
    "es": "Gestión y organización",
    "fr": "Management et organisation",
    "de": "Management und Organisation",
    "it": "Management e organizzazione",
    "ru": "Менеджмент и организация",
    "pt": "Gestão e organização",
    "ko": "경영 및 조직",
    "vi": "Quản trị và tổ chức",
    "th": "การจัดการและองค์การ",
    "el": "Διοίκηση και Οργάνωση"
  },
  "BM.MKT": {
    "zh-CN": "市场营销",
    "en": "Marketing",
    "jp": "マーケティング",
    "es": "Marketing",
    "fr": "Marketing",
    "de": "Marketing",
    "it": "Marketing",
    "ru": "Маркетинг",
    "pt": "Marketing",
    "ko": "마케팅",
    "vi": "Tiếp thị",
    "th": "การตลาด",
    "el": "Μάρκετινγκ"
  },
  "BM.ACC": {
    "zh-CN": "会计与审计",
    "en": "Accounting & Auditing",
    "jp": "会計・監査",
    "es": "Contabilidad y auditoría",
    "fr": "Comptabilité et audit",
    "de": "Rechnungswesen und Wirtschaftsprüfung",
    "it": "Contabilità e revisione contabile",
    "ru": "Бухгалтерский учёт и аудит",
    "pt": "Contabilidade e auditoria",
    "ko": "회계 및 감사",
    "vi": "Kế toán và kiểm toán",
    "th": "การบัญชีและการตรวจสอบบัญชี",
    "el": "Λογιστική και Ελεγκτική"
  },
  "BM.LOG": {
    "zh-CN": "物流与供应链管理",
    "en": "Logistics & Supply Chain Management",
    "jp": "物流・サプライチェーン管理",
    "es": "Logística y gestión de la cadena de suministro",
    "fr": "Logistique et gestion de la chaîne d'approvisionnement",
    "de": "Logistik und Supply-Chain-Management",
    "it": "Logistica e gestione della catena di fornitura",
    "ru": "Логистика и управление цепями поставок",
    "pt": "Logística e gestão da cadeia de suprimentos",
    "ko": "물류 및 공급망 관리",
    "vi": "Logistics và quản trị chuỗi cung ứng",
    "th": "โลจิสติกส์และการจัดการซัพพลายเชน",
    "el": "Εφοδιαστική και Διαχείριση Εφοδιαστικής Αλυσίδας"
  },
  "BM.OPS": {
    "zh-CN": "运营与流程管理",
    "en": "Operations & Process Management",
    "jp": "オペレーションズ・プロセスマネジメント",
    "es": "Gestión de operaciones y procesos",
    "fr": "Gestion des opérations et des processus",
    "de": "Operations- und Prozessmanagement",
    "it": "Gestione delle operazioni e dei processi",
    "ru": "Управление операциями и процессами",
    "pt": "Gestão de operações e processos",
    "ko": "운영 및 프로세스 관리",
    "vi": "Quản trị vận hành và quản lý quy trình",
    "th": "การจัดการการดำเนินงานและกระบวนการ",
    "el": "Διοίκηση Λειτουργιών και Διαχείριση Διαδικασιών"
  },
  "BM.INNO": {
    "zh-CN": "创业与创新",
    "en": "Entrepreneurship & Innovation",
    "jp": "起業・イノベーション",
    "es": "Emprendimiento e innovación",
    "fr": "Entrepreneuriat et innovation",
    "de": "Unternehmertum und Innovation",
    "it": "Imprenditorialità e innovazione",
    "ru": "Предпринимательство и инновации",
    "pt": "Empreendedorismo e inovação",
    "ko": "창업 및 혁신",
    "vi": "Khởi nghiệp và đổi mới sáng tạo",
    "th": "ผู้ประกอบการและนวัตกรรม",
    "el": "Επιχειρηματικότητα και Καινοτομία"
  },
  "BM.RISK": {
    "zh-CN": "风险、合规与治理",
    "en": "Risk, Compliance & Governance",
    "jp": "リスク・コンプライアンス・ガバナンス",
    "es": "Riesgo, cumplimiento y gobernanza",
    "fr": "Risque, conformité et gouvernance",
    "de": "Risiko, Compliance und Governance",
    "it": "Rischio, conformità e governance",
    "ru": "Риск, комплаенс и корпоративное управление",
    "pt": "Risco, conformidade e governança",
    "ko": "리스크, 컴플라이언스 및 거버넌스",
    "vi": "Rủi ro, tuân thủ và quản trị",
    "th": "ความเสี่ยง การปฏิบัติตามข้อกำหนด และธรรมาภิบาล",
    "el": "Κίνδυνος, Συμμόρφωση και Διακυβέρνηση"
  },

  // FG
  "FG.GEN": {
    "zh-CN": "通用词汇",
    "en": "General",
    "jp": "一般語彙",
    "es": "Vocabulario general",
    "fr": "Vocabulaire général",
    "de": "Allgemeiner Wortschatz",
    "it": "Vocabolario generale",
    "ru": "Общая лексика",
    "pt": "Vocabulário geral",
    "ko": "일반 어휘",
    "vi": "Từ vựng chung",
    "th": "คำศัพท์ทั่วไป",
    "el": "Γενικό λεξιλόγιο"
  },
  "FG.ACAD": {
    "zh-CN": "学术通用词汇",
    "en": "Academic General",
    "jp": "学術一般語彙",
    "es": "Vocabulario académico general",
    "fr": "Vocabulaire académique général",
    "de": "Allgemeiner akademischer Wortschatz",
    "it": "Vocabolario accademico generale",
    "ru": "Общенаучная лексика",
    "pt": "Vocabulário acadêmico geral",
    "ko": "학술 일반 어휘",
    "vi": "Từ vựng học thuật chung",
    "th": "คำศัพท์วิชาการทั่วไป",
    "el": "Γενικό Ακαδημαϊκό Λεξιλόγιο"
  },
  "FG.METH": {
    "zh-CN": "研究方法",
    "en": "Research Methods",
    "jp": "研究方法",
    "es": "Métodos de investigación",
    "fr": "Méthodes de recherche",
    "de": "Forschungsmethoden",
    "it": "Metodi di ricerca",
    "ru": "Методы исследования",
    "pt": "Métodos de pesquisa",
    "ko": "연구 방법",
    "vi": "Phương pháp nghiên cứu",
    "th": "ระเบียบวิธีวิจัย",
    "el": "Μεθοδολογία Έρευνας"
  },
  "FG.DISC": {
    "zh-CN": "文本与话语元语言",
    "en": "Text & Discourse Meta",
    "jp": "テキスト・談話メタ言語",
    "es": "Metalinguaje de texto y discurso",
    "fr": "Méta-langage du texte et du discours",
    "de": "Text- und Diskurs-Metasprache",
    "it": "Metalinguaggio del testo e del discorso",
    "ru": "Метаязык текста и дискурса",
    "pt": "Metalinguagem de texto e discurso",
    "ko": "텍스트 및 담화 메타언어",
    "vi": "Siêu ngôn ngữ văn bản và diễn ngôn",
    "th": "เมตาภาษาของข้อความและวาทกรรม",
    "el": "Μεταγλώσσα Κειμένου και Λόγου"
  },
  "FG.LOGIC": {
    "zh-CN": "形式逻辑",
    "en": "Formal Logic",
    "jp": "形式論理学",
    "es": "Lógica formal",
    "fr": "Logique formelle",
    "de": "Formale Logik",
    "it": "Logica formale",
    "ru": "Формальная логика",
    "pt": "Lógica formal",
    "ko": "형식 논리학",
    "vi": "Logic hình thức",
    "th": "ตรรกศาสตร์เชิงรูปแบบ",
    "el": "Τυπική Λογική"
  }
};
